# MDP Settings
MAX_EPISODES = 1000
MAX_STEPS_PER_EPISODE = 100

# Agent Hyperparameters
LEARNING_RATE = 0.01
DISCOUNT_FACTOR = 0.99
EXPLORATION_RATE = 1.0
EXPLORATION_DECAY = 0.995
MIN_EXPLORATION_RATE = 0.01

# Logging Settings
LOG_LEVEL = "INFO"
LOG_FILE = "agent.log"
